name: Publish GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    permissions:
      # ocaml/setup-ocaml/deploy-doc pushes to the gh-pages branch
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: OCaml 4.13.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x
          dune-cache: false # true does not publish pages consistently

      - name: Deploy odoc to GitHub Pages
        uses: ocaml/setup-ocaml/deploy-doc@v2
